version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
init:
- ps: git config --global core.autocrlf true
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- nuget restore
build:
  verbosity: minimal
artifacts:
- path: 'Tvl.VisualStudio.InheritanceMargin\bin\Release\Tvl.VisualStudio.InheritanceMargin.vsix'
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config
